name: project_app_flutter
description: "Mototek Application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  cloud_firestore: ^4.17.5
  url_launcher: ^6.2.6
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.1
  intl: ^0.19.0
  android_intent_plus: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"